//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        [Display(Name = "Appointment-id")]
        public int appointment_id { get; set; }
        [Display(Name = "Appointment-Date")]
        public Nullable<System.DateTime> a_date { get; set; }
        [Display(Name = "Hospital Name")]
        public Nullable<int> hospital_id { get; set; }
        [Display(Name = "Doctor Name")]
        public Nullable<int> doctor_id { get; set; }
        [Display(Name = "Patient Name")]
        public Nullable<int> patient_id { get; set; }
        [Display(Name = "Status")]
        public string appointment_status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
