//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int doctor_id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string df_name { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string dl_name { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string d_email { get; set; }
        [Required]
        [Display(Name = "Mobile No.")]
        public Nullable<long> dc_number { get; set; }
        [Required]
        [Display(Name = "Degree Name")]
        public Nullable<int> Degree_id { get; set; }
        [Required]
        [Display(Name = "speciality")]
        public Nullable<int> speciality_id { get; set; }
        [Required]
        [Display(Name = "Hospital Name")]
        public Nullable<int> hospital_id { get; set; }
        [Required]
        [Display(Name = "Image")]
        public string d_profile_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual speciality speciality { get; set; }
    }
}
