//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Doctors = new HashSet<Doctor>();
        }
    
       
        public int hospital_id { get; set; }
        [Required]
        [Display(Name ="Hospital Name")]
        public string h_name { get; set; }
        [Required]
        [Display(Name = "Number")]
        public Nullable<long> hc_number { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string h_email { get; set; }
        [Required]
        [Display(Name = "Password")]
        public string h_password { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string h_address { get; set; }
        [Required]
        [Display(Name = "State")]
        public Nullable<int> state_id { get; set; }
        [Required]
        [Display(Name = "City")]
        public Nullable<int> city_id { get; set; }
        [Required]
        [Display(Name = "Hospital Image")]
        public string h_profile_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual State State { get; set; }
    }
}
