//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.EDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int patient_id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string pf_name { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string pl_name { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string p_email { get; set; }
        [Required]
        [Display(Name = "Mobile No.")]
        public Nullable<long> pc_number { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string p_address { get; set; }
        [Required]
        [Display(Name = "Password")]
        public string p_password { get; set; }
        [Required]
        [Display(Name = "State")]
        public Nullable<int> state_id { get; set; }
        [Required]
        [Display(Name = "City")]
        public Nullable<int> city_id { get; set; }
        [Required]
        [Display(Name = "Image")]
        public string p_profile_image { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public string p_gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual City City { get; set; }
        public virtual State State { get; set; }
    }
}
