//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajaxcrudopration.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class companydetail
    {
        public int companyid { get; set; }
        public Nullable<int> empid { get; set; }
        public string company_name { get; set; }
        public string company_location { get; set; }
        public string company_city { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
